spring.application.name=nexus
spring.datasource.url=jdbc:postgresql://localhost:5432/nexus
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.redis.host=localhost
spring.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

logging.file.name=logs/nexus.log
logging.level.root=OFF
logging.level.com.example.nexus=INFO
logging.level.org.springframework.kafka=ERROR